language: common-lisp
sudo: required

env:
  matrix:
    - LISP=ccl COVERALLS=true

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;

script:
  - cl -l cl-locale -l prove -l cl-coveralls
       -e '(progn
            (setf prove:*debug-on-error* t
                  *debugger-hook* (lambda (c h)
                                    (declare (ignore c h))
                                    (uiop:quit -1)))
            (or (coveralls:with-coveralls (:exclude "t")
                  (prove:run :cl-locale-test))
                (uiop:quit -1)))'
